// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73xdGP9Q5fZ1cPjXq85afw
// Component: 8IO5gDfq_fdx
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: jbktukOjJD-L/component
import Client from "../../Client"; // plasmic-import: n-zDNABtnjj6/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: qO1rwRcK1KDF/component
import FooterMain from "../../FooterMain"; // plasmic-import: 9-zI42kgeb0s/component
import { useScreenVariants as useScreenVariantshFppFalB91Q } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: H-fppFalB91Q/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 73xdGP9Q5fZ1cPjXq85afw/projectcss
import sty from "./PlasmicClients.module.css"; // plasmic-import: 8IO5gDfq_fdx/css
import airbnbsvgOhZ8RYDd3J0H from "./images/airbnbsvg.svg"; // plasmic-import: ohZ8rYDd3j0H/picture
import asanasvg1Ebb3PFmdUmf from "./images/asanasvg.svg"; // plasmic-import: 1ebb3pFmdUmf/picture
import disneysvgUsFtMcx7HLo from "./images/disneysvg.svg"; // plasmic-import: UsFt_MCX7HLo/picture
import instacartsvgZC3NQjcikHgd from "./images/instacartsvg.svg"; // plasmic-import: zC3nQjcikHgd/picture

createPlasmicElementProxy;

export const PlasmicClients__VariantProps = new Array();

export const PlasmicClients__ArgProps = new Array();

const $$ = {};

function PlasmicClients__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshFppFalB91Q()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"banner"}
            data-plasmic-override={overrides.banner}
            className={classNames(projectcss.all, sty.banner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vYqbl)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Clients"
                    : "Clients"}
                </h1>
                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem Ipsum is simply dummy text of the printing and typesetting "
                    : "Lorem Ipsum is simply dummy text of the printing and typesetting "}
                </div>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__s1P9O)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__djKrp)}
            >
              <div className={classNames(projectcss.all, sty.column__nmjNa)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rvk3D)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__mihZc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___6RmvE)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__cPnU
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__xbMd
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__zOh2Q)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wPaO7)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__kWlfa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___0VIqm)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__gh0KY
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__wH4V
                          )}
                        >
                          {"Client name 2"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__uFzdt)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xTbiL)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__rjGek)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__fPAoI)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client__bfooo
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__itNzI
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__d0JF)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tt2W)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__fjlV)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__cgBmu)}
                    >
                      <Client
                        className={classNames(
                          "__wab_instance",
                          sty.client___2Rqhx
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__r0Rq
                          )}
                        >
                          {"Client name"}
                        </h2>
                      </Client>
                    </div>
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"clientsSection5"}
            data-plasmic-override={overrides.clientsSection5}
            hasGap={true}
            className={classNames(projectcss.all, sty.clientsSection5)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ccddw)}
            >
              <div className={classNames(projectcss.all, sty.columns__faam3)}>
                <div className={classNames(projectcss.all, sty.column__tvm6A)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ddBy2
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "More client's we've worked with"
                      : "More client's we've worked with"}
                  </h2>
                </div>
                <div className={classNames(projectcss.all, sty.column__wcEk8)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__p0U63)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pcO5E)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__l0Qh)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: airbnbsvgOhZ8RYDd3J0H,
                          fullWidth: 300,
                          fullHeight: 96,
                          aspectRatio: 3.125
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__oqSU)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: asanasvg1Ebb3PFmdUmf,
                          fullWidth: 300,
                          fullHeight: 62,
                          aspectRatio: 4.863636
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9RIv0)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: disneysvgUsFtMcx7HLo,
                          fullWidth: 300,
                          fullHeight: 124,
                          aspectRatio: 2.41655
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__fOm7G)}
                        displayHeight={"48px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: instacartsvgZC3NQjcikHgd,
                          fullWidth: 300,
                          fullHeight: 60,
                          aspectRatio: 4.961538
                        }}
                      />
                    </Stack__>
                  </div>
                </div>
              </div>
            </Stack__>
          </Stack__>
          <div
            data-plasmic-name={"footerTopSection"}
            data-plasmic-override={overrides.footerTopSection}
            className={classNames(projectcss.all, sty.footerTopSection)}
          >
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "banner",
    "foreground2",
    "h1",
    "text",
    "clientsSection5",
    "footerTopSection",
    "homeFooterTop",
    "footerMain"
  ],

  header: ["header"],
  banner: ["banner", "foreground2", "h1", "text"],
  foreground2: ["foreground2", "h1", "text"],
  h1: ["h1"],
  text: ["text"],
  clientsSection5: ["clientsSection5"],
  footerTopSection: ["footerTopSection", "homeFooterTop"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicClients__ArgProps,
          internalVariantPropNames: PlasmicClients__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicClients__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicClients";
  } else {
    func.displayName = `PlasmicClients.${nodeName}`;
  }
  return func;
}

export const PlasmicClients = Object.assign(
  // Top-level PlasmicClients renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    banner: makeNodeComponent("banner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    text: makeNodeComponent("text"),
    clientsSection5: makeNodeComponent("clientsSection5"),
    footerTopSection: makeNodeComponent("footerTopSection"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),
    // Metadata about props expected for PlasmicClients
    internalVariantProps: PlasmicClients__VariantProps,
    internalArgProps: PlasmicClients__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Clients",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicClients;
/* prettier-ignore-end */
