// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73xdGP9Q5fZ1cPjXq85afw
// Component: r83EKkQQAzf_
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 73xdGP9Q5fZ1cPjXq85afw/projectcss
import sty from "./PlasmicServiceDark.module.css"; // plasmic-import: r83EKkQQAzf_/css

createPlasmicElementProxy;

export const PlasmicServiceDark__VariantProps = new Array();

export const PlasmicServiceDark__ArgProps = new Array("children", "slot");

const $$ = {};

function PlasmicServiceDark__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <h3
        data-plasmic-name={"h3"}
        data-plasmic-override={overrides.h3}
        className={classNames(projectcss.all, projectcss.h3, sty.h3)}
      >
        {renderPlasmicSlot({
          defaultContents: "Service name",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </h3>
      <div
        data-plasmic-name={"bdrLight"}
        data-plasmic-override={overrides.bdrLight}
        className={classNames(projectcss.all, sty.bdrLight)}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
          value: args.slot,
          className: classNames(sty.slotTargetSlot)
        })}
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root", "h3", "bdrLight", "freeBox"],
  h3: ["h3"],
  bdrLight: ["bdrLight"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServiceDark__ArgProps,
          internalVariantPropNames: PlasmicServiceDark__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServiceDark__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceDark";
  } else {
    func.displayName = `PlasmicServiceDark.${nodeName}`;
  }
  return func;
}

export const PlasmicServiceDark = Object.assign(
  // Top-level PlasmicServiceDark renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    bdrLight: makeNodeComponent("bdrLight"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicServiceDark
    internalVariantProps: PlasmicServiceDark__VariantProps,
    internalArgProps: PlasmicServiceDark__ArgProps
  }
);

export default PlasmicServiceDark;
/* prettier-ignore-end */
