// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 73xdGP9Q5fZ1cPjXq85afw
// Component: M3sFsVcPKJLa
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import BlueBdr from "../../BlueBdr"; // plasmic-import: yjrn5NihbWxB/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 73xdGP9Q5fZ1cPjXq85afw/projectcss
import sty from "./PlasmicServiceWhite.module.css"; // plasmic-import: M3sFsVcPKJLa/css

createPlasmicElementProxy;

export const PlasmicServiceWhite__VariantProps = new Array();

export const PlasmicServiceWhite__ArgProps = new Array(
  "children",
  "slot",
  "slot2"
);

const $$ = {};

function PlasmicServiceWhite__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <h3
        data-plasmic-name={"h3"}
        data-plasmic-override={overrides.h3}
        className={classNames(projectcss.all, projectcss.h3, sty.h3)}
      >
        {renderPlasmicSlot({
          defaultContents: "Service name",
          value: args.children
        })}
      </h3>
      <div className={classNames(projectcss.all, sty.freeBox___5D6Cu)}>
        {renderPlasmicSlot({
          defaultContents: (
            <BlueBdr
              className={classNames("__wab_instance", sty.blueBdr__xezlz)}
            />
          ),

          value: args.slot
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__uR49C)}>
        {renderPlasmicSlot({
          defaultContents:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
          value: args.slot2
        })}
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root", "h3"],
  h3: ["h3"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServiceWhite__ArgProps,
          internalVariantPropNames: PlasmicServiceWhite__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServiceWhite__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceWhite";
  } else {
    func.displayName = `PlasmicServiceWhite.${nodeName}`;
  }
  return func;
}

export const PlasmicServiceWhite = Object.assign(
  // Top-level PlasmicServiceWhite renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    // Metadata about props expected for PlasmicServiceWhite
    internalVariantProps: PlasmicServiceWhite__VariantProps,
    internalArgProps: PlasmicServiceWhite__ArgProps
  }
);

export default PlasmicServiceWhite;
/* prettier-ignore-end */
